[env]
# Postgres built-in env vars
PGDATA = "{{ env.BASE_DIR }}/.postgres_data"
PGUSER = "postgres"
# Custom database env vars
POSTGRES_USER = "postgres"
POSTGRES_DB = "library_dev"
# Keep iex history
ERL_AFLAGS = "-kernel shell_history enabled"
