[env]
CSV_DATA = "{{ env.BASE_DIR }}/tmp/csv"
# Postgres built-in env vars
PGDATA = "{{ env.BASE_DIR }}/tmp/postgres"
PGUSER = "postgres"
# Custom database env vars
POSTGRES_USER = "postgres"
POSTGRES_DB = "library_dev"
# Keep iex history
ERL_AFLAGS = "-kernel shell_history enabled"
# ash_cloak / cloak
CLOAK_KEY = "kB3nc0fEkw9cZVrfUeo6DCBDfGT86hokmyEkeVHzz0Y="
