version: "3.9"

services:
  app:
    build:
      target: vscode
    volumes:
      - vscode:/home/app-user/.vscode-server/extensions
      - vscode-insiders:/home/app-user/.vscode-server-insiders/extensions
    environment:
      ERL_AFLAGS: -kernel shell_history enabled

volumes:
  vscode:
  vscode-insiders:
